### ISSUE TITLE
Error: "CreateFile forcedpacks/: The system cannot find the file specified."

### ISSUE THREAD

**Issue by NhanAZ** [bedrock-tool/bedrocktool#101]
```yaml
Input Command: -debug packs  ❌
Enter Server: play.mojang.com
time="2023-09-07T12:22:24+07:00" level=error msg="CreateFile forcedpacks/: The system cannot find the file specified."
time="2023-09-07T12:22:24+07:00" level=info msg="Press Enter to exit."
```
```yaml
Input Command: -extra-debug packs  ❌
Enter Server: play.mojang.com
time="2023-09-07T12:21:47+07:00" level=error msg="CreateFile forcedpacks/: The system cannot find the file specified."
time="2023-09-07T12:21:47+07:00" level=info msg="Press Enter to exit."
```
