### ISSUE TITLE
Command line interface error

### ISSUE THREAD

**Issue by NhanAZ** [bedrock-tool/bedrocktool#194]
I don't know how to describe this error. But look at the reproduction steps below I think you'll understand what's going on.

**To Reproduce**
1. Type any command and press Enter (I use `packs` in this step)
![image](https://github.com/bedrock-tool/bedrocktool/assets/60387689/4bac0901-2606-4217-abf1-a9cc41c79c32)
Here `Enter Server:` should be a line break.
2. Since I use `packs`, I will enter a random server address in this step (I enter `poggit.pmmp.io`) and press Enter
![image](https://github.com/bedrock-tool/bedrocktool/assets/60387689/b5165daa-6734-456b-85b2-2492ec7d17d1)
Here the message `INFO[0473] Connecting to poggit.pmmp.io:19132` should be a newline.
The previous `Input Command: packs` message also disappeared.

What happens in the `bedrocktool.log` file looks quite chaotic?
```yaml
time="2024-07-01T12:50:10+07:00" level=info msg="Bedrocktool Version 1.38.0-16" part=main
Available Commands:
	chat-log	logs chat to a file

	update	self updates to latest version

	skins	download skins from players on a server

	capture	capture packets in a pcap file

	debug-proxy	verbose debug packets

	realm-address	gets realms address

	list-realms	prints all realms you have access to

	packs	download resource packs from a server

	worlds	download a world from a server

	trans	

	blind-proxy	raknet proxy

Use 'bedrocktool <command>' to run a command
Input Command: 
Input Command: p[K
Input Command: p  ❌[K[4D
Input Command: pa[K
Input Command: pa  ❌[K[4D
Input Command: pak[K
Input Command: pak  ❌[K[4D
Input Command: pa[K
Input Command: pa  ❌[K[4D
Input Command: pac[K
Input Command: pac  ❌[K[4D
Input Command: pack[K
Input Command: pack  ❌[K[4D
Input Command: packs[K
Input Command: packs  ✅[K[4D
Enter Server: 
Enter Server: p[K
Enter Server: po[K
Enter Server: pog[K
Enter Server: pogg[K
Enter Server: poggi[K
Enter Server: poggit[K
Enter Server: poggit.[K
Enter Server: poggit.p[K
Enter Server: poggit.pm[K
Enter Server: poggit.pmm[K
Enter Server: poggit.pmmp[K
Enter Server: poggit.pmmp.[K
Enter Server: poggit.pmmp.i[K
Enter Server: poggit.pmmp.io[K
Enter Server: poggit.pmmp.io  ❌[K[4D
Enter Server: poggit.pmmp.io  ✅[K[4D
time="2024-07-01T12:58:03+07:00" level=info msg="Connecting to poggit.pmmp.io:19132"
time="2024-07-01T12:58:16+07:00" level=error msg="dial raknet: dial udp: lookup poggit.pmmp.io: i/o timeout"
time="2024-07-01T12:58:16+07:00" level=info msg="Press Enter to exit."
```
